config/routes.rb
Rails.application.routes.draw do
  resources :astros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astro.rb
class Astro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/astros_controller.rb
class AstrosController < ApplicationController
  before_action :set_astro, only: [:show, :edit, :update, :destroy]

  # GET /astros
  # GET /astros.json
  def index
    @astros = Astro.all
  end

  # GET /astros/1
  # GET /astros/1.json
  def show
  end

  # GET /astros/new
  def new
    @astro = Astro.new
  end

  # GET /astros/1/edit
  def edit
  end

  # POST /astros
  # POST /astros.json
  def create
    @astro = Astro.new(astro_params)

    respond_to do |format|
      if @astro.save
        format.html { redirect_to @astro, notice: 'Astro was successfully created.' }
        format.json { render :show, status: :created, location: @astro }
      else
        format.html { render :new }
        format.json { render json: @astro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /astros/1
  # PATCH/PUT /astros/1.json
  def update
    respond_to do |format|
      if @astro.update(astro_params)
        format.html { redirect_to @astro, notice: 'Astro was successfully updated.' }
        format.json { render :show, status: :ok, location: @astro }
      else
        format.html { render :edit }
        format.json { render json: @astro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /astros/1
  # DELETE /astros/1.json
  def destroy
    @astro.destroy
    respond_to do |format|
      format.html { redirect_to astros_url, notice: 'Astro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_astro
      @astro = Astro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def astro_params
      params.require(:astro).permit(:punk, :mango, :sticker)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/astros_helper.rb
module AstrosHelper
end

app/views/astros/_form.html.erb
<%= form_for(astro) do |f| %>
  <% if astro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(astro.errors.count, "error") %> prohibited this astro from being saved:</h2>

      <ul>
      <% astro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :punk %>
    <%= f.text_field :punk %>
  </div>

  <div class="field">
    <%= f.label :mango %>
    <%= f.text_field :mango %>
  </div>

  <div class="field">
    <%= f.label :sticker %>
    <%= f.text_field :sticker %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/astros/edit.html.erb
<h1>Editing Astro</h1>

<%= render 'form', astro: @astro %>

<%= link_to 'Show', @astro %> |
<%= link_to 'Back', astros_path %>

app/views/astros/index.html.erb
<div style="width: 100vw; height: 100vh; display: flex; justify-content: center; align-items: center;">
  <form target="_blank" action="http://52.78.22.145:80/paygate/new" method="GET" name="form_payment" id="form_payment">
    <select class="form-control" name="paygate[amount]" id="amount">
      <option disabled>선택하세요</option>
      <option value="1000">1포인트 (1,000원)</option>
      <option value="9500">10포인트 (9,500원)</option>
      <option value="19000">20포인트 (19,000원)</option>
      <option value="45000">50포인트 (45,000원)</option>
      <option value="100000">월 무제한 (100,000원)</option>
    </select>
    <input type="text" name="paygate[user_key]" placeholder="user_key">
    <input type="text" name="paygate[pg]" placeholder="pg">
    <input type="text" name="paygate[pay_method]" placeholder="pay_method">
    <input type="hidden" name="paygate[merchant_uid]" value="merchant">
    <input type="hidden" name="paygate[product_name]" value="쿠니목소리4개">
    <input type="hidden" name="paygate[buyer_name]" value="이한결">
    <input type="hidden" name="paygate[buyer_tel]" value="010-3344-2809">
    <input type="hidden" name="paygate[buyer_email]" value="test@cooni.com">
    <input type="hidden" name="paygate[buyer_postcode]" value="44344">
    <button id="paybutton" class="btn btn-login">결제하기</button>
  </form>
</div>

<hr>

<p id="notice"><%= notice %></p>

<h1>Astros</h1>

<table>
  <thead>
    <tr>
      <th>Punk</th>
      <th>Mango</th>
      <th>Sticker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @astros.each do |astro| %>
      <tr>
        <td><%= astro.punk %></td>
        <td><%= astro.mango %></td>
        <td><%= astro.sticker %></td>
        <td><%= link_to 'Show', astro %></td>
        <td><%= link_to 'Edit', edit_astro_path(astro) %></td>
        <td><%= link_to 'Destroy', astro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Astro', new_astro_path %>

app/views/astros/new.html.erb
<h1>New Astro</h1>

<%= render 'form', astro: @astro %>

<%= link_to 'Back', astros_path %>

app/views/astros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Punk:</strong>
  <%= @astro.punk %>
</p>

<p>
  <strong>Mango:</strong>
  <%= @astro.mango %>
</p>

<p>
  <strong>Sticker:</strong>
  <%= @astro.sticker %>
</p>

<%= link_to 'Edit', edit_astro_path(@astro) %> |
<%= link_to 'Back', astros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapistranoAstro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>